<#
.SYNOPSIS
  One-time local-dev setup. Reads the deployed env's real endpoints and writes the gitignored
  local config files. Twin of dev-local-setup.sh. Idempotent.
.EXAMPLE
  .\dev-local-setup.ps1
  .\dev-local-setup.ps1 prod
#>
[CmdletBinding()]
param([Parameter(Position = 0)][string]$Environment = 'dev')

. "$PSScriptRoot\lib.ps1"

$envName = Require-EnvArg $Environment
Confirm-Subscription

$repoRoot = (Resolve-Path (Join-Path $script:InfraDir '..')).Path
$rg = Get-EnvRg $envName

Write-Log 'Checking tooling...'
foreach ($c in @('az', 'dotnet', 'node', 'npm')) { Require-Command $c }
if (-not (Get-Command func -ErrorAction SilentlyContinue)) {
    Write-Warn "Azure Functions Core Tools ('func') not found - you won't be able to run Smx.Functions."
}
if (-not (Get-Command azurite -ErrorAction SilentlyContinue)) {
    Write-Warn 'azurite not found (npm i -g azurite) - Smx.Functions needs a local storage emulator.'
}

Write-Log "Reading endpoints from $rg..."
$cosmosName = az cosmosdb list -g $rg --query '[0].name' -o tsv
if ([string]::IsNullOrWhiteSpace($cosmosName)) { Die "No Cosmos account in $rg - is env '$envName' deployed?" }
$cosmosEp = az cosmosdb show -g $rg -n $cosmosName --query documentEndpoint -o tsv
$searchEp = "https://$(az search service list -g $rg --query '[0].name' -o tsv).search.windows.net"
$foundryEp = az cognitiveservices account list -g $rg --query '[0].properties.endpoint' -o tsv
$bronze = az storage account list -g $rg --query '[?isHnsEnabled].name | [0]' -o tsv

# Reachability is the whole story for local dev: harden puts most services behind private
# endpoints, and a laptop is not in the VNet. Report it plainly instead of letting the app
# fail later with an opaque timeout.
$cosmosPublic = az cosmosdb show -g $rg -n $cosmosName --query publicNetworkAccess -o tsv
$searchPublic = az search service list -g $rg --query '[0].publicNetworkAccess' -o tsv
$foundryPublic = az cognitiveservices account list -g $rg --query '[0].properties.publicNetworkAccess' -o tsv
Write-Log 'Service reachability from this machine:'
foreach ($s in @(@{N = 'Cosmos'; V = $cosmosPublic }, @{N = 'Search'; V = $searchPublic }, @{N = 'Foundry'; V = $foundryPublic })) {
    $state = if ($s.V -ieq 'enabled') { 'reachable' } else { 'PRIVATE (VNet only)' }
    Write-Host ('  {0,-10} {1}' -f $s.N, $state)
}

# Cosmos is the one the local backend genuinely needs. Its firewall is an IP allowlist, so a
# changed office/VPN IP silently turns every query into a timeout.
if ($cosmosPublic -ieq 'enabled') {
    $myIp = Get-DeployerIp
    $allowed = @(az cosmosdb show -g $rg -n $cosmosName --query 'ipRules[].ipAddressOrRange' -o tsv)
    if ($myIp -and ($allowed -notcontains $myIp)) {
        Write-Warn "Your IP $myIp is NOT on the Cosmos allowlist ($($allowed -join ', '))."
        Write-Warn 'The local backend will hang on every Cosmos call. Fix with:'
        $newList = (@($allowed) + $myIp | Where-Object { $_ }) -join ','
        Write-Warn "  az cosmosdb update -g $rg -n $cosmosName --ip-range-filter `"$newList`""
    }
}

Write-Log 'Writing local config...'
New-Item -ItemType Directory -Path (Join-Path $repoRoot '.dev-local') -Force | Out-Null

# Environment variables, not appsettings.Development.json: those files are tracked (they hold
# logging levels), and a setup script must never clobber a tracked file. Env vars are also how
# the app is configured in Azure, so local and cloud read config through the same path.
# dev-local.ps1 loads this before launching the backend.
$backendEnv = @"
# Generated by dev-local-setup.ps1 from $rg. Regenerate; do not hand-edit.
ASPNETCORE_ENVIRONMENT=Development
COSMOS_ACCOUNT_ENDPOINT=$cosmosEp
SEARCH_ENDPOINT=$searchEp
FOUNDRY_ENDPOINT=$foundryEp
COSMOS_DATABASE=smx
RECORD_CONTAINER=record
COMPATIBILITY_CONTAINER=ref-compatibility
"@

$functionsCfg = [ordered]@{
    IsEncrypted = $false
    Values      = [ordered]@{
        AzureWebJobsStorage      = 'UseDevelopmentStorage=true'
        FUNCTIONS_WORKER_RUNTIME = 'dotnet-isolated'
        COSMOS_ACCOUNT_ENDPOINT  = $cosmosEp
        COSMOS_DATABASE          = 'smx'
        SEARCH_ENDPOINT          = $searchEp
        FOUNDRY_ENDPOINT         = $foundryEp
        BRONZE_ACCOUNT_NAME      = $bronze
        BRONZE_FILESYSTEM        = 'bronze'
        SDS_DRY_RUN              = 'true'
        REG_DRY_RUN              = 'true'
    }
} | ConvertTo-Json -Depth 4

# Set-Content -Encoding UTF8 writes a BOM on Windows PowerShell, which trips JSON parsers.
function Write-Utf8NoBom {
    param([string]$Path, [string]$Content)
    [IO.File]::WriteAllText($Path, $Content, (New-Object Text.UTF8Encoding($false)))
}

Write-Utf8NoBom (Join-Path $repoRoot '.dev-local\backend.env') $backendEnv
Write-Utf8NoBom (Join-Path $repoRoot 'src\Smx.Functions\local.settings.json') $functionsCfg

Write-Log 'Wrote (both gitignored):'
Write-Log '  .dev-local/backend.env            (loaded by dev-local.ps1)'
Write-Log '  src/Smx.Functions/local.settings.json'
Write-Log ''
Write-Log "Local auth is your own 'az login' (DefaultAzureCredential) - no keys are written."
Write-Log 'Next: .\dev-local.ps1 up'
