#!/usr/bin/env bash
set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

# One-time local-dev setup. Reads the deployed env's real endpoints and writes the gitignored
# local config files. Idempotent — re-run it whenever the deployed env changes.
#
# Usage: dev-local-setup.sh [dev|prod]   (default: dev)
ENV="$(require_env_arg "${1:-dev}")"
confirm_subscription

REPO_ROOT="$(cd "${INFRA_DIR}/.." && pwd)"
RG="$(printf 'rg-%s-%s-%s' "${NAME_PREFIX}" "${ENV}" "${REGION_SHORT}")"

log "Checking tooling..."
for c in az dotnet node npm; do require_cmd "$c"; done
command -v func >/dev/null 2>&1 || warn "Azure Functions Core Tools ('func') not found — you won't be able to run Smx.Functions."
command -v azurite >/dev/null 2>&1 || warn "azurite not found (npm i -g azurite) — Smx.Functions needs a local storage emulator."

log "Reading endpoints from ${RG}..."
COSMOS_NAME="$(az cosmosdb list -g "${RG}" --query '[0].name' -o tsv)"
[[ -n "${COSMOS_NAME}" ]] || die "No Cosmos account in ${RG} — is env '${ENV}' deployed?"
COSMOS_EP="$(az cosmosdb show -g "${RG}" -n "${COSMOS_NAME}" --query documentEndpoint -o tsv)"
SEARCH_EP="https://$(az search service list -g "${RG}" --query '[0].name' -o tsv).search.windows.net"
FOUNDRY_EP="$(az cognitiveservices account list -g "${RG}" --query '[0].properties.endpoint' -o tsv)"
BRONZE="$(az storage account list -g "${RG}" --query '[?isHnsEnabled].name | [0]' -o tsv)"

# Reachability is the whole story for local dev: harden.sh puts most services behind private
# endpoints, and a laptop is not in the VNet. Report it plainly instead of letting the app
# fail later with an opaque timeout.
reachable() { # <display> <public-network-access-value>
  if [[ "${2,,}" == "enabled" ]]; then printf '  %-10s reachable\n' "$1"; return 0; fi
  printf '  %-10s PRIVATE (VNet only)\n' "$1"; return 1
}
log "Service reachability from this machine:"
COSMOS_PUBLIC="$(az cosmosdb show -g "${RG}" -n "${COSMOS_NAME}" --query publicNetworkAccess -o tsv)"
SEARCH_PUBLIC="$(az search service list -g "${RG}" --query '[0].publicNetworkAccess' -o tsv)"
FOUNDRY_PUBLIC="$(az cognitiveservices account list -g "${RG}" --query '[0].properties.publicNetworkAccess' -o tsv)"
reachable Cosmos  "${COSMOS_PUBLIC}"  || true
reachable Search  "${SEARCH_PUBLIC}"  || true
reachable Foundry "${FOUNDRY_PUBLIC}" || true

# Cosmos is the one the local backend genuinely needs. Its firewall is an IP allowlist, so a
# changed office/VPN IP silently turns every query into a timeout.
if [[ "${COSMOS_PUBLIC,,}" == "enabled" ]]; then
  MY_IP="$(detect_ip)"
  ALLOWED="$(az cosmosdb show -g "${RG}" -n "${COSMOS_NAME}" --query "ipRules[].ipAddressOrRange" -o tsv | tr '\n' ' ')"
  if [[ -n "${MY_IP}" && " ${ALLOWED} " != *" ${MY_IP} "* ]]; then
    warn "Your IP ${MY_IP} is NOT on the Cosmos allowlist (${ALLOWED:-none})."
    warn "The local backend will hang on every Cosmos call. Fix with:"
    warn "  az cosmosdb update -g ${RG} -n ${COSMOS_NAME} --ip-range-filter \"${ALLOWED// /,}${ALLOWED:+,}${MY_IP}\""
  fi
fi

log "Writing local config..."
mkdir -p "${REPO_ROOT}/.dev-local"

# Environment variables, not appsettings.Development.json: those files are tracked (they hold
# logging levels), and a setup script must never clobber a tracked file. Env vars are also how
# the app is configured in Azure, so local and cloud read config through the same path.
# dev-local.sh sources this before launching the backend.
# Plain KEY=value (dotenv), NOT `export K=v`: the .ps1 twin writes and reads the same file,
# so the format has to be shell-agnostic.
cat > "${REPO_ROOT}/.dev-local/backend.env" <<ENVFILE
# Generated by dev-local-setup.sh from ${RG}. Regenerate; do not hand-edit.
ASPNETCORE_ENVIRONMENT=Development
COSMOS_ACCOUNT_ENDPOINT=${COSMOS_EP}
SEARCH_ENDPOINT=${SEARCH_EP}
FOUNDRY_ENDPOINT=${FOUNDRY_EP}
COSMOS_DATABASE=smx
RECORD_CONTAINER=record
COMPATIBILITY_CONTAINER=ref-compatibility
ENVFILE

cat > "${REPO_ROOT}/src/Smx.Functions/local.settings.json" <<JSON
{
  "IsEncrypted": false,
  "Values": {
    "AzureWebJobsStorage": "UseDevelopmentStorage=true",
    "FUNCTIONS_WORKER_RUNTIME": "dotnet-isolated",
    "COSMOS_ACCOUNT_ENDPOINT": "${COSMOS_EP}",
    "COSMOS_DATABASE": "smx",
    "SEARCH_ENDPOINT": "${SEARCH_EP}",
    "FOUNDRY_ENDPOINT": "${FOUNDRY_EP}",
    "BRONZE_ACCOUNT_NAME": "${BRONZE}",
    "BRONZE_FILESYSTEM": "bronze",
    "SDS_DRY_RUN": "true",
    "REG_DRY_RUN": "true"
  }
}
JSON

log "Wrote (both gitignored):"
log "  .dev-local/backend.env            (exported by dev-local.sh)"
log "  src/Smx.Functions/local.settings.json"
log ""
log "Local auth is your own 'az login' (DefaultAzureCredential) — no keys are written."
log "Next: ./dev-local.sh up"
